kolibri: Add options for desktop auth plugin
endlessm/eos-image-builder pull request #47
Opened 2021-12-13 22:40 UTC by manuq

Add option for partners that wish to force Kolibri superadmin user for
regular system users.

If the option is set in the image INI file, it will be added to
Kolibri's options INI file.

https://phabricator.endlessm.com/T32805

2021-12-13 22:40 UTC, manuq commented
Marking as draft because this depends on https://github.com/endlessm/kolibri-desktop-auth-plugin/pull/9 and on releasing that plugin to PyPi.

2022-01-27 00:52 UTC, dylanmccall commented
It kind of looks like this needs a new Phabricator ticket, but we can work on merging this now.

2022-01-27 09:14 UTC, danigm approved these changes

2022-02-15 21:58 UTC, dylanmccall requested changes

2022-02-15 21:58 UTC, dylanmccall commented on hooks/image/60-kolibri-content
> +fi
This hook is only going to run if `EIB_KOLIBRI_INSTALL_CHANNELS` is set, which is not the case for all of the images where we expect `EIB_KOLIBRI_DESKTOP_AUTH_PLUGIN_REGULAR_USERS_CAN_MANAGE_CONTENT` to be true. Instead, I think we should do this in its own hook, similar to #55.

2022-02-15 21:58 UTC, dylanmccall commented on hooks/image/60-kolibri-content
> +kolibri plugin enable kolibri_desktop_auth_plugin
:+1:

2022-02-18 01:31 UTC, dylanmccall commented
I built on top of this in #60, changing the option name and using a new hook to generate our options.ini file.

2022-02-18 01:31 UTC, closed without merging